services:
  - docker

before_install:
  - tar -czvf frc-2019-jetson-src.tar.gz src
  - docker pull ros:kinetic-perception-xenial
  - docker build --build-arg projecttarball=./frc-2019-jetson-src.tar.gz -t arctos:ros-build .
  - docker run arctos:ros-build > frc-2019-jetson-build.tar.gz
